name: Publish Cocoapods

on:
  push:
    tags:
      - '*'

jobs:
  publish:
  
    runs-on: macos-latest
    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7'
        
      - uses: actions/checkout@v2

      - name: Install Cocoapods
        run: gem install cocoapods
        
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
